### ISSUE TITLE
Client cannot connect to the server

### ISSUE THREAD

**Issue by Boryczko** [MycroftAI/personal-backend#10]
Hi I have changed all settings and disabled SSL (for client - conf http instead of https, and for backend server conf ssl from true to false).
Client cannot connect to the server. Server log:
127.0.0.1 - - [16/Jan/2019 21:04:14] "GET /v0.1/device/ HTTP/1.1" 404 -
127.0.0.1 - - [16/Jan/2019 21:04:19] "GET /v0.1/device//subscription HTTP/1.1" 404 -
127.0.0.1 - - [16/Jan/2019 21:04:20] "GET /v0.1/device/ HTTP/1.1" 404 -
...
127.0.0.1 - - [16/Jan/2019 21:10:14] "GET /v0.1/device//setting HTTP/1.1" 404 -
127.0.0.1 - - [16/Jan/2019 21:10:14] "GET /v0.1/device/ HTTP/1.1" 404 -

**Comment by JarbasAl** [comment]
which host are you using?

127.0.0.1 will only allow access from same machine, you probably want to use 0.0.0.0

also check firewall settings in case it's relevant, not sure where you are running the server and client, please give more details

**Comment by Boryczko** [comment]
I use ubuntu 18.04 with default settings (firewall is not installed) - the newest version after update & upgrade.
I don't understand why in log I can see 127.0.0.1, because I use 0.0.0.0:6712 without ssl for 
client("url": "http://0.0.0.0:6712") <<----->> backend(http://0.0.0.0:6712/) 
communication.

**Comment by el-tocino** [comment]
your client config has the server at 0.0.0.0? That should be 127.0.0.1 (or the regular ip of the server). What's in the server logs?

**Comment by JarbasAl** [comment]
@Boryczko please confirm this is fixed by https://github.com/MycroftAI/personal-backend/pull/25
