### ISSUE TITLE
secret key and salt

### ISSUE THREAD

**Issue by dragonsKnight5** [MycroftAI/personal-backend#23]
Hi,
Decided to have go getting this running, however I can't workout
where secret key and salt are coming from

I've had a look in some of the files and still can't work it out

I could use some guidance
Best Regards
dragonsKnight5

**Comment by JarbasAl** [comment]
https://github.com/MycroftAI/personal-backend/blob/master/personal_mycroft_backend/settings.py#L53

you should also be able to change it in the config file

**Comment by JarbasAl** [comment]
deprecated by #44
