### ISSUE TITLE
Privacy improvements

### ISSUE THREAD

**Issue by flatsiedatsie** [MycroftAI/personal-backend#34]
The current code could be more privacy friendly. Issues:

- A connection is made to https://ipapi.co/json/ in backend utils. Solution: assume a country code. Not the end of the world?
- The HTML that flask generates tries to download bulma and font_awesome from a CDN. Solution: store these files locally.

**Comment by flatsiedatsie** [comment]
I've created a pull request to fix the CDN issue:
https://github.com/MycroftAI/personal-backend/pull/35

**Comment by JarbasAl** [comment]
"solved" by #44  - frontend is deprecated
and #42 - ip geolocation updated and using [geolite2](https://dev.maxmind.com/geoip/geoip2/geolite2/)
