### ISSUE TITLE
ref/link to roadmap? (Question)

### ISSUE THREAD

**Issue by fermulator** [MycroftAI/personal-backend#40]
Just to clarify, is THIS "personal-backend" the same as "personal-server" as per https://mycroft.ai/blog/many-roads-one-destination/ ?

https://docs.google.com/document/d/1VJsk9xmFig1qAP-wH_SAB-3xyKRx28Z47IwlJWJMqOM/edit

@penrods

**Comment by krisgesling** [comment]
Yes, personal backend and personal server are the same.

**Comment by JarbasAl** [comment]
Official mycroft backend has been open sourced, read the [blog post](https://mycroft.ai/blog/open-sourcing-the-mycroft-backend/)

This repo is an alternative to the backend meant for personal usage, eventually this will become an out of the box solution to run completely offline / self hosted

If you need to manage multiple user accounts this project is not for you! If you just want a divorce from mycroft.home on your devices then this might help

There isn't (yet) and official roadmap for this repo

feel free to re-open the issue if you have further questions
