### ISSUE TITLE
Can I donate to this project?

### ISSUE THREAD

**Issue by iot-resister** [MycroftAI/personal-backend#55]
Awesome project!

**Comment by JarbasAl** [comment]
original developer/maintainer here, i am unclear on the status of this project, with the opening up of Selene as the official mycroft backend i moved development to https://github.com/OpenVoiceOS/OVOS-local-backend

note that this repo should be a fork of that one but was a bare clone, i believe this repo is not being maintained anymore but someone from the Mycroft team needs to confirm that

If you want to donate to mycroft you can do that in their website

**Comment by JarbasAl** [comment]
@krisgesling can you either archive this repo or setup a warning asking for maintainers?

**Comment by krisgesling** [comment]
Hey there, glad you're enjoying Mycroft. 

We are not actively working on this project and have no plans to in the short to medium term. I'll add a better warning on the main README.

If you're looking to donate to Mycroft as a whole, then please considering becoming a monthly subscriber via your account at https://home.mycroft.ai/profile
One-time donations can also be made on the website: https://mycroft.ai/product/donate-to-open-source/

If you want to support the development of the Personal Backend specifically then the OVOS Local Backend repo that Jarbas mentioned is the best place for that.
